plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.finalprojectt1'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.finalprojectt1"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
//implementacion del retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.6.4'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.3'

    //implementacion del GLide
    implementation 'com.github.bumptech.glide:glide:4.14.2'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.14.2'

    dependencies {
        // Dependencias de Room
        def room_version = "2.6.0"  // Usa la última versión disponible

        implementation "androidx.room:room-runtime:$room_version"
        annotationProcessor "androidx.room:room-compiler:$room_version" // Para usar Room con Java


        // Room para soporte de RxJava, si lo necesitas
        implementation "androidx.room:room-rxjava2:$room_version" // RxJava 2.x
        implementation "androidx.room:room-rxjava3:$room_version" // RxJava 3.x

        // Para migraciones de Room
        implementation "androidx.room:room-paging:$room_version"
    }

}